modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/nanite/Flat-Bedrock/issues"
license="MIT License"
[[mods]]
modId="flatbedrock"
version="${version}"
displayName="Flat Bedrock"
displayURL="https://www.curseforge.com/minecraft/mc-mods/flat-bedrock" #optional
description='''
This mod changes the vanilia bedrock generator to make flat bedrock in the overworld and nether'''
[[dependencies.flatbedrock]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.flatbedrock]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"
