modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/nanite/Flat-Bedrock/issues"
license="MIT License"

[[mods]]
modId="flatbedrock"
version="${version}"
displayName="Flat Bedrock"
displayURL="https://www.curseforge.com/minecraft/mc-mods/flat-bedrock" #optional
description='''
This mod changes the vanilia bedrock generator to make flat bedrock in the overworld and nether'''

[[dependencies.flatbedrock]]
modId="neoforge"
required=true
versionRange="[20.6,)"
ordering="NONE"
side="BOTH"

[[dependencies.flatbedrock]]
modId="minecraft"
required=true
versionRange="[1.20.6,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "flatbedrock-common.mixins.json"
